
# Site settings
title: DevComanda Community
email: info@devcomanda.com
description: >- # this means to ignore newlines until "baseurl:"
  Сообщество ребят, которые интересуются разработкой на Java и не только.
  На своем опыте мы поняли, что учиться намного легче вместе.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devcomanda.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: devcomanda1
github_username:  devcomanda
facebook_username: devcomanda
google_analytics: UA-124320630-1


# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["CNAME", "readme.md", "Gemfile", "Gemfile.lock"]