
# Site settings
title: DevComanda Community
email: info@devcomanda.com
description: >- # this means to ignore newlines until "baseurl:"
  Сообщество ребят, которые интересуются разработкой на Java и не только.
  На своем опыте мы поняли, что учиться намного легче вместе.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devcomanda.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-124320630-1

social_links:
  github: devcomanda
  twitter:  devcomanda1
  facebook: devcomanda
  youtube_channel: UCU8N0JiUME2zgkXYA3AqRJQ
  youtube_name: devcomanda
    
# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["CNAME", "readme.md", "Gemfile", "Gemfile.lock"]